let boxes = document.getElementsByClassName("box"); //By getElementsByClassName

boxes[2].style.backgroundColor = "yellow"

document.getElementById("fourth").style.backgroundColor = "blue" //By getElementById
document.getElementById("fourth").style.color = "white" //By getElementById

document.querySelector(".box").style.backgroundColor = "purple" //By querySelector
document.querySelector(".box").style.color = "white " //By querySelector

 
document.querySelectorAll(".box").forEach(e => {  //By querySelectorAll
    e.style.backgroundColor = "grey"
    e.style.color = "white"
});


e = document.getElementsByTagName("div");

console.log(e[4].matches("#fourth")) //element.matches() 

console.log(e[3].closest(".container")) //element.closest()

console.log(document.querySelector(".container").contains(e[4])) //elementA.contains(elementB)

console.log(document.querySelector(".container").contains(document.querySelector("body"))) //false

console.log(document.querySelector("body").contains(document.querySelector(".container"))) //true


//Excercise 7
//que 1

document.getElementById("firstElement").style.color = "red"

//que 2
//Added a table without tbody and after viewing its page source in the web browser it successfully shows the tbody which was generated by the browser

//que 3

p1 = document.childNodes[1].childNodes[2].childNodes[7].childNodes[1] 
p2 = document.childNodes[1].childNodes[2].childNodes[7].childNodes[5] 

p1.style.color = "green"
p2.style.color = "green"

//que 4

document.querySelectorAll(".lists").forEach(e=>{
    e.style.color = "cyan"
})



